"""modificando el campo nombre_categoria para que sea unique

Revision ID: 08bc9d1c2f0a
Revises: c4150873ce92
Create Date: 2025-11-06 14:28:19.845732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bc9d1c2f0a'
down_revision = 'c4150873ce92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_categoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
