"""add: agregando el campo telefono al modelo usuario

Revision ID: 38fac120e24e
Revises: 08bc9d1c2f0a
Create Date: 2025-11-08 16:00:56.997875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fac120e24e'
down_revision = '08bc9d1c2f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
