"""Initial migration

Revision ID: eb1bd6f6abbd
Revises: 
Create Date: 2025-08-21 19:57:02.016488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1bd6f6abbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.String(length=36), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.Column('Descripcion_cat', sa.String(length=150), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.String(length=36), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('direccion'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('rol', sa.String(length=40), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.String(length=36), nullable=False),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.String(length=36), nullable=False),
    sa.Column('imagen_url', sa.String(length=200), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('movimientos',
    sa.Column('id_movimiento', sa.String(length=36), nullable=False),
    sa.Column('id_producto', sa.String(length=36), nullable=False),
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=60), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=60), nullable=True),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('producto_proveedor',
    sa.Column('id_producto_proveedor', sa.String(length=36), nullable=False),
    sa.Column('id_producto', sa.String(length=36), nullable=False),
    sa.Column('id_proveedor', sa.String(length=36), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tiempo_entrega_dias', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('preferido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_producto_proveedor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_proveedor')
    op.drop_table('movimientos')
    op.drop_table('productos')
    op.drop_table('usuarios')
    op.drop_table('proveedor')
    op.drop_table('categorias')
    # ### end Alembic commands ###
