"""agregando el campo de telefono al modelo de usuario

Revision ID: f6923ba297d0
Revises: 38fac120e24e
Create Date: 2025-11-13 16:39:58.333726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6923ba297d0'
down_revision = '38fac120e24e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
